-- CREATE PROJECTS TABLE
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    technologies TEXT[] NOT NULL DEFAULT '{}',
    features TEXT[] NOT NULL DEFAULT '{}',
    aim TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CREATE EDUCATION TABLE
CREATE TABLE public.education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree TEXT NOT NULL,
    institution TEXT NOT NULL,
    year TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CREATE EXPERIENCE TABLE
CREATE TABLE public.experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    period TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CREATE CERTIFICATES TABLE
CREATE TABLE public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT NOT NULL,
    issue_date TEXT NOT NULL,
    credential_url TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Create Policies (Read for everyone, Write/Modify for authenticated users only)
-- Projects policies
CREATE POLICY "Allow public read access for projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated users on projects" ON public.projects FOR ALL USING (auth.role() = 'authenticated');

-- Education policies
CREATE POLICY "Allow public read access for education" ON public.education FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated users on education" ON public.education FOR ALL USING (auth.role() = 'authenticated');

-- Experience policies
CREATE POLICY "Allow public read access for experience" ON public.experience FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated users on experience" ON public.experience FOR ALL USING (auth.role() = 'authenticated');

-- Certificates policies
CREATE POLICY "Allow public read access for certificates" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated users on certificates" ON public.certificates FOR ALL USING (auth.role() = 'authenticated');
